# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EMDS
                                 A QGIS plugin
 EMDS client plugin for QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-01-16
        copyright            : (C) 2019 by Mountain View Business Group
        email                : info@mountain-viewgroup.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load EMDS class from file EMDS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .EMDS import EMDS
    return EMDS(iface)
